### ISSUE TITLE
Support for this Helm chart in EKS v1.24

### ISSUE THREAD

**Issue by grv180290** [aws-observability/aws-otel-helm-charts#104]
We are currently using the ADOT collector on our 1.23 EKS cluster and we are using this to send OTLP traces to Amazon Opensearch. We are successfully able to ingest the traces and see the service map for our application. 

However, since 1.23 is nearing end of support and we are planning to move to v1.24 of EKS. 
Docker is not supported as a container runtime on 1.24 and we plan to use containerd as our container runtime.

Currently in the values.yaml file, I see that this Helm chart mounts  "/var/lib/docker" and "var/run/docker.sock" as volumes to the collector Daemonset. 

Since docker is not supported on EKS version 1.24 and later, will this Collector daemonset still function as intended. 
Can someone officially verify this Helm chart support for v1.24

**Comment by joebowbeer** [comment]
Fixed by #60
