### ISSUE TITLE
Enable IRSA by providing different serviceAccount annotations for fluent-bit and ADOT

### ISSUE THREAD

**Issue by youwalther65** [aws-observability/aws-otel-helm-charts#14]
In order to make IRSA possible we need dedicated annotation for fluent-bit and adot-collector-sa ServiceAccount

Currently only the following is available in values.yaml

serviceAccount:
  create: true
  annotations: {}
  name: ""

Please provide a serviceAccount section for fluent-bit including annotation and add annotations into already existing adot-collector-sa ServiceAccount section

Currently it is only possible to attach IAM policy to worker node profile.

**Comment by ruthvik17** [comment]
Added reviewers for the above PRs.

**Comment by ruthvik17** [comment]
Reviewed and Merged the PRs stated above.
