### ISSUE TITLE
  Add enabled attribute for adotCollector section as well

### ISSUE THREAD

**Issue by youwalther65** [aws-observability/aws-otel-helm-charts#15]
fluentbit and fargateLog already contains an attribute enabled which can be set to false or true.
Please add same attribute "enabled" to adotCollector section as well so on can decide what should be installed for all 3 components.

**Comment by ruthvik17** [comment]
@youwalther65 , I think you can turn the adotCollector off by setting the attribute "enabled" in adotCollector.daemonSet to false. 
Please see here: https://github.com/aws-observability/aws-otel-helm-charts/blob/master/charts/adot-exporter-for-eks-on-ec2/values.yaml#L183

If both the "enabled attributes for daemonSet and Sidecar is turned to false, the adotCollector will not deploy

**Comment by ruthvik17** [comment]
Closing this issue. Please file a new one for further requests.
