### ISSUE TITLE
Add OTEL Prometheus to Helm chart for Container Insights Prometheus

### ISSUE THREAD

**Issue by youwalther65** [aws-observability/aws-otel-helm-charts#16]
Add OTEL Prometheus to Helm chart for full Container Insights Prometheus functionality

**Comment by ruthvik17** [comment]
Hi @youwalther65 , The Helm chart with support for AMP is currently in development. See this: https://github.com/aws-observability/aws-otel-helm-charts/pull/13

**Comment by ruthvik17** [comment]
Closing this issue since the new release of the helm chart has support for AMP.

**Comment by youwalther65** [comment]
Team, it is not all about AMP. It is about to scrape Prometheus endpoints as well as described [here](https://aws-otel.github.io/docs/getting-started/container-insights/eks-prometheus) or [here](https://aws.amazon.com/blogs/containers/introducing-cloudwatch-container-insights-prometheus-support-with-aws-distro-for-opentelemetry-on-amazon-ecs-and-amazon-eks/) Currently I don't see ths mentioned in your docs or Helm values.yaml
