### ISSUE TITLE
ENHANCEMENT: Provide capability in Helm chart to configure the retention policy for Log Groups

### ISSUE THREAD

**Issue by sunnygoel87** [aws-observability/aws-otel-helm-charts#23]
Hi Team,

By default, CloudWatch retains the logs forever. Many of our customers expressed interest in retaining the logs for a specific duration in CloudWatch service to save the storage cost. We implemented that by configuring the **log_retention_days** parameter in FluentBit agent config file while installing the agent separately on the EKS cluster. 

It will be great if the Helm chart can also support this capability. I can work on this enhancement. Please let me know if that works for the team. Thanks.

**Comment by alolita** [comment]
Hi @sunnygoel87 thanks for your interest to contribute. Please feel free to file a PR for adding the retention policy for logs and we'd be happy to review.

**Comment by ruthvik17** [comment]
Hi @sunnygoel87 , the following Pull Request: https://github.com/aws-observability/aws-otel-helm-charts/pull/22
 adds log_retention_days as an option to the Helm Chart.

**Comment by sunnygoel87** [comment]
ah, even i worked on this @ruthvik17.  I was about to submit the PR. No worries. By when will it get merged ?
