### ISSUE TITLE
Update the docs with correct values

### ISSUE THREAD

**Issue by steveellis** [aws-observability/aws-otel-helm-charts#33]
Noticed this while working on #32. I believe the doc [here](https://github.com/aws-observability/aws-otel-helm-charts/blob/master/charts/adot-exporter-for-eks-on-ec2/documentation/metrics_to_cloudwatch_amp.md#sending-metrics-and-logs-to-cloudwatch-container-insights-only) has incorrect values. I'm fairly sure I wasn't able to get the adot collector started unless I used these instead of what are listed.

The doc suggests that:
* `adotCollector.daemonSet.service.metrics.receivers` is `awscontainerinsight`
* `adotCollector.daemonSet.service.metrics.exporters` is `awsemfexporter`.

I think the correct values are:
* `adotCollector.daemonSet.service.metrics.receivers` is `awscontainerinsightreceiver`
* `adotCollector.daemonSet.service.metrics.exporters` is `awsemf`.

**Comment by steveellis** [comment]
There's also a typo: "expoerters"

**Comment by sunnygoel87** [comment]
@steveellis , You're absolutely right. Thanks for brining it to our attention. We'll fix it quickly.

**Comment by sunnygoel87** [comment]
@steveellis , We've fixed it. Please take a look and let me know if you see any other discrepancy in the documentation. Thanks.

**Comment by ruthvik17** [comment]
Closing this issue since the errors are fixed. Please feel free to open a new issue for further requests.
