### ISSUE TITLE
FluentBit crashes on deployment

### ISSUE THREAD

**Issue by ruthvik17** [aws-observability/aws-otel-helm-charts#42]
**Describe the bug**

![image](https://user-images.githubusercontent.com/28427103/162840677-fa71c862-58d4-4b49-9731-072790a67f44.png)

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

Updated the receivers and the exporters to offload metrics and logs to CloudWatch. 

helm install \  
  [RELEASE_NAME] [REPO_NAME]/adot-exporter-for-eks-on-ec2 \   
  --set clusterName=[CLUSTER_NAME] --set awsRegion=[AWS_REGION]

**What did you expect to see?**
A clear and concise description of what you expected to see.
FluentBit and Collector pods are both running

**What did you see instead?**
A clear and concise description of what you saw instead.
FluentBit pods do not deploy.
**Environment**
Describe any aspect of your environment relevant to the problem.

**Additional context**

**Comment by sunnygoel87** [comment]
@ruthvik17 , We can close this now..

**Comment by ruthvik17** [comment]
Closing the issue since fix has been added.
