### ISSUE TITLE
containerd support

### ISSUE THREAD

**Issue by alanpilawa** [aws-observability/aws-otel-helm-charts#48]
As per AWS documentation on [dockershim deprecation](https://docs.aws.amazon.com/eks/latest/userguide/dockershim-deprecation.html): "Amazon EKS AMIs that are officially published will have containerd as the only runtime starting with version 1.23. This is targeted for end of the second quarter of 2022"

My customer has tested the [aws-otel-helm-charts](https://github.com/aws-observability/aws-otel-helm-charts) solution with only containerd used by the cluster and the solution stopped working - probably because of mounts to docker-specific host paths.

The customer is asking, if/when the solution will be adjusted to use only containerd

**Comment by vasireddy99** [comment]
Hello,

Thanks for explaining the issue In detail, we are currently working on supporting the `containerd` runtime as the dockershim will be deprecated as you mentioned. will provide the info here as soon as we have any update. please stay tuned.

**Comment by vasireddy99** [comment]
Support for running on clusters with containerd runtime is now available. Closing this Issue.
