### ISSUE TITLE
Unable to install helm chart for cloudwatch metrics without AMP/Prometheus

### ISSUE THREAD

**Issue by shapirov103** [aws-observability/aws-otel-helm-charts#56]
**Describe the bug**
Following the [documentation](https://github.com/aws-observability/aws-otel-helm-charts/blob/main/charts/adot-exporter-for-eks-on-ec2/documentation/metrics_to_cloudwatch_amp.md#offload-metrics-to-amazon-cloudwatch) I am getting a failure for the adot collector add-on. It used to work for version 0.1.0 of the chart, but fails with all higher versions

**Steps to reproduce**
Follow documentation for offloading metrics to amazon cloudwatch. I can see that the instructions for the two sections are identical:
[CloudWatch](https://github.com/aws-observability/aws-otel-helm-charts/blob/main/charts/adot-exporter-for-eks-on-ec2/documentation/metrics_to_cloudwatch_amp.md#offload-metrics-to-amazon-cloudwatch)
[CloudWatch and AMP](https://github.com/aws-observability/aws-otel-helm-charts/blob/main/charts/adot-exporter-for-eks-on-ec2/documentation/metrics_to_cloudwatch_amp.md#offload-metrics-to-both-cloudwatch-and-amazon-managed-prometheusamp).

**What did you expect to see?**
Expected an option to enable CloudWatch metrics only. 

**What did you see instead?**
Appears that AMP exporter is active by default
adot collector daemonset failed with the following error message:

```
builder/exporters_builder.go:40    Exporter is starting...    {"kind": "exporter", "name": "awsprometheusremotewrite"}    │
│ Error: cannot start exporters: invalid endpoint: "http://some.url:9411/api/prom/push"                                                                         │
│ 2022/07/13 02:26:20 application run finished with error: cannot start exporters: invalid endpoint: "http://some.url:9411/api/prom/push"                       │
│ Stream closed EOF for amazon-metrics/adot-collector-daemonset-n54d9 (adot-collector-container)  
```

**Environment**
EKS 1.21

**Additional context**

**Comment by erichsueh3** [comment]
We encourage use of [ADOT with EKS addons](https://docs.aws.amazon.com/eks/latest/userguide/opentelemetry.html) instead of this helm chart going forward

**Comment by shapirov103** [comment]
> We encourage use of [ADOT with EKS addons](https://docs.aws.amazon.com/eks/latest/userguide/opentelemetry.html) instead of this helm chart going forward

That is what we had to do eventually, but it would be nice either call out that this particular feature won't work, or deprecate the chart altogether.

**Comment by vasireddy99** [comment]
Hi @shapirov103 can you please share the `values.yaml` that you have used to install chart?

**Comment by AbubakrSamsodien** [comment]
i too didnt use a values file, i just followed documentation, my logs in cloudwatch is working but no metrics showed up on container-insights.
the ADOT addon requires cert-manager to be installed, does this mean i wouldnt be able to create eks from scratch with ADOT addon installed? it has to be an update?

can we get the documentation for this implementation updated?
