### ISSUE TITLE
Failed to update lock: leases.coordination.k8s.io is forbidden

### ISSUE THREAD

**Issue by AbubakrSamsodien** [aws-observability/aws-otel-helm-charts#63]
**Describe the bug**
tried to helm install adot, after i attached the CloudWatchAgentServerPolicy policy to the eks ng, i could see the metrics and logs on cloudwatch, however i see these logs when i output the logs of the collector. not really sure how it affects functionality. 

kubectl logs adot-collector-daemonset-c98m8 -n amazon-metrics
E0917 19:25:08.199040       1 leaderelection.go:367] Failed to update lock: leases.coordination.k8s.io is forbidden: User "system:serviceaccount:amazon-metrics:adot-collector-sa" cannot create resource "leases" in API group "coordination.k8s.io" in the namespace "amazon-metrics"
E0917 19:25:17.959812       1 leaderelection.go:334] error initially creating leader election record: leases.coordination.k8s.io is forbidden: User "system:serviceaccount:amazon-metrics:adot-collector-sa" cannot create resource "leases" in API group "coordination.k8s.io" in the namespace "amazon-metrics"

**Steps to reproduce**
eks 1.21
helm install \
container-insights aws-observability/adot-exporter-for-eks-on-ec2 \
-f values.yml

same default values file with recievers and exporters updated for cloudwatch

    ampexporters:
      namespaces: ""
      endpoint: ""
      resourcetootel: false
      authenticator: "sigv4auth"
    service:
      metrics:
        receivers: ["awscontainerinsightreceiver"]
        processors: ["batch/metrics"]
        exporters: ["awsemf"]
      extensions: ["health_check", "sigv4auth"]

**What did you expect to see?**
no failed or error logs

**What did you see instead?**
failed and error logs

**Comment by imZack** [comment]
It's due to some missing permission in ClusterRole. I've created PRs and got merged. See https://github.com/aws-observability/aws-otel-helm-charts/blob/main/charts/adot-exporter-for-eks-on-ec2/templates/adot-collector/clusterrole.yaml#L29-L35

It's not released yet, btw.

**Comment by xpicio** [comment]
Hello, @imZack i have a similar stuff, but on retrieving resource:

```
E0927 06:01:59.110995       1 leaderelection.go:330] error retrieving resource lock amazon-metrics/otel-container-insight-clusterleader: leases.coordination.k8s.io "otel-container-insight-clusterleader" is forbidden: User "system:serviceaccount:amazon-metrics:adot-collector" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "amazon-metrics"
```

Is it the same issue ?

**Comment by xpicio** [comment]
@imZack i just patched `adot-collector-role` with the new rules from  [here](https://github.com/aws-observability/aws-otel-helm-charts/blob/main/charts/adot-exporter-for-eks-on-ec2/templates/adot-collector/clusterrole.yaml#L29-L35) and it's seems it's working.

Just after the patch i got this log message:
```
I0927 06:11:05.518611       1 event.go:285] Event(v1.ObjectReference{Kind:"Lease", Namespace:"amazon-metrics", Name:"otel-container-insight-clusterleader", UID:"8b44e64e-ded1-4209-9b18-99b520de4c5f", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"246983", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' ip-10-0-0-154.eu-south-1.compute.internal became leader
```

**Comment by imZack** [comment]
@xpicio Sounds good. Let's wait for the new release, so we don't have to patch manually. @vasireddy99

**Comment by vasireddy99** [comment]
The release with this change has been is out last month. Please reopen this issue if it still persists
