### ISSUE TITLE
awsemf exporter send data to the wrong region

### ISSUE THREAD

**Issue by xpicio** [aws-observability/aws-otel-helm-charts#68]
Hello, i have a cluster on `eu-south-1` region, but some feature of ContainerInsight is still not deployed to this region; so i setup the chart to send log and metrics to `eu-west-1`. The log are send correctly to the right region, but the metrics are still on eu-south-1. It's seems you missed to propagate the value of `awsRegion` to the `awsemf` exporter config.

https://github.com/aws-observability/aws-otel-helm-charts/blob/ecde735f07d72f87b63086ccfece111cdbc3e6be/charts/adot-exporter-for-eks-on-ec2/templates/adot-collector/configmap.yaml#L36-L46

Just append `region` property to `awsemf` exporter:
```
region: {{ .Values.awsRegion }}
```

Hope this help, have a nice day

**Comment by vasireddy99** [comment]
Thanks for creating the issue, a fix has been done to resolve this issue.
