### ISSUE TITLE
IDMS is hardcoded to v1

### ISSUE THREAD

**Issue by Vlaaaaaaad** [aws-observability/aws-otel-helm-charts#7]
**Describe the bug**
In the FluentBit config, IDMS is hardcoded to `v1`. When using IDMS `v2`, the `v1` endpoint is no longer working and FluentBit complains.

**Steps to reproduce**
Deploy the Helm chart with FluentBit enabled, on a cluster where IDMSv2 is enabled.

**What did you expect to see?**
The helm chart working and logs appearing in CloudWatch Logs.

**What did you see instead?**
```
[error] [filter:aws:aws.2] Could not retrieve ec2 metadata from IMDS
```

**Environment**

EKS version: `1.21` 
EC2 workers: Managed Node Group, version ` 1.21`, using Bottlerocket OS 1.4.2 (aws-k8s-1.21), with IDMSv2 enabled.

**Additional context**

https://github.com/fluent/fluent-bit/issues/2840

Note hardcoded `v1` string:
https://github.com/aws-observability/aws-otel-helm-charts/blob/317dab9ac386ae2557763a97185d58fd18bd2454/charts/adot-exporter-for-eks-on-ec2/templates/aws-for-fluent-bit/configmap.yaml#L127-L130

**Comment by alolita** [comment]
Hi @Vlaaaaaaad Thanks for testing. Good catch! Will get this fixed.
