### ISSUE TITLE
Bottlerocket and containerd support

### ISSUE THREAD

**Issue by Vlaaaaaaad** [aws-observability/aws-otel-helm-charts#8]
Hi,

Making this a general issue and not a bug report, as I did not have time to re-test. There is a large possibility I am wrong here, and I apologize if that is the case!

Does the `adot-exporter-for-eks-on-ec2` chart support container metrics from EC2 hosts using Bottlerocket and containerd?

I am seeing no [`containerdsock` mount in `values.yaml`](https://github.com/aws-observability/aws-otel-helm-charts/blob/master/charts/adot-exporter-for-eks-on-ec2/values.yaml#L220-L241), and that is in-line with the [_No pod metrics when using Bottlerocket for Amazon EKS_ common error](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights-troubleshooting.html), and it would be in-line with the experience I had with CloudWatch Container Insights.

**Comment by alolita** [comment]
Hi @Vlaaaaaaad thanks for the suggestions. Bottlerocket and containerd metrics are not supported yet. We will take a look.
